global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: preview
  enableKeyVaults: true

java:
  releaseNameOverride: idam-testing-support-api
  applicationPort: 5000
  image: 'hmctspublic.azurecr.io/idam/idam-testing-support-api:latest'
  ingressHost: idam-testing-support-api.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: idam
  environment:
    IDAM_API_URL: http://idam-api.service.core-compute-{{ .Values.global.environment }}.internal
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://idam-web-public.service.core-compute-{{ .Values.global.environment }}.internal/o/jwks
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_IDAMTESTINGSUPPORTAPI_TOKENURI: http://idam-web-public.service.core-compute-{{ .Values.global.environment }}.internal/o/token
  keyVaults:
    "idam-idam":
      resourceGroup: idam-idam
      excludeEnvironmentSuffix: false
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: idam-testing-support-api-POSTGRES-HOST
          alias: DATASOURCE_HOST
        - name: idam-testing-support-api-POSTGRES-PORT
          alias: DATASOURCE_PORT
        - name: idam-testing-support-api-POSTGRES-DATABASE
          alias: DATASOURCE_DATABASE
        - name: idam-testing-support-api-POSTGRES-USER
          alias: spring.datasource.username
        - name: idam-testing-support-api-POSTGRES-PASS
          alias: spring.datasource.password
        - name: notify-api-key
          alias: notify.key
        - name: idam-testing-support-api-client-secret
          alias: spring.security.oauth2.client.registration.idam-testing-support-api.client-secret
