# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  releaseNameOverride: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_API_URL: https://idam-api.service.core-compute-aat.internal
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://idam-web-public.service.core-compute-aat.internal/o/jwks

