global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: preview
  enableKeyVaults: true

java:
  releaseNameOverride: idam-testing-support-api
  applicationPort: 5000
  image: 'hmctspublic.azurecr.io/idam/idam-testing-support-api:latest'
  ingressHost: idam-testing-support-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: idam
  environment:
  keyVaults:
    "idam-idam":
      resourceGroup: idam-idam
      excludeEnvironmentSuffix: false
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
