java:
  releaseNameOverride: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devApplicationInsightsInstrumentKeyName: DUMMY_APPLICATIONINSIGHTS_DUMMYKEY
  devApplicationInsightsInstrumentKey: '00000001-0001-0001-0001-000000000001'
  environment:
    SCHEDULER_ENABLED: false
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://idam-web-public.aat.platform.hmcts.net/o/jwks
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_IDAMTESTINGSUPPORTAPI_TOKENURI: https://idam-web-public.aat.platform.hmcts.net/o/token
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_RDUSERPROFILEAPI_TOKENURI: https://idam-web-public.aat.platform.hmcts.net/o/token
    RD_USERPROFILE_API_URL: http://rd-user-profile-api-aat.service.core-compute-aat.internal
    RD_CASEWORKER_API_URL: http://rd-caseworker-ref-api-aat.service.core-compute-aat.internal
    IDAM_S2SAUTH_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
  keyVaults:
    "idam-idam":
      resourceGroup: idam-idam
      excludeEnvironmentSuffix: false
      secrets:
        - name: AppInsightsConnectionString
          alias: app-insights-connection-string
        - name: idam-testing-support-api-POSTGRES-HOST-v2
          alias: DATASOURCE_HOST
        - name: idam-testing-support-api-POSTGRES-PORT-v2
          alias: DATASOURCE_PORT
        - name: idam-testing-support-api-POSTGRES-DATABASE-v2
          alias: DATASOURCE_DATABASE
        - name: idam-testing-support-api-POSTGRES-USER-v2
          alias: spring.datasource.username
        - name: idam-testing-support-api-POSTGRES-PASS-v2
          alias: spring.datasource.password
        - name: notify-api-key
          alias: notify.key
        - name: idam-testing-support-api-client-secret
          alias: spring.security.oauth2.client.registration.idam-testing-support-api.client-secret
        - name: idam-testing-support-api-client-secret
          alias: spring.security.oauth2.client.registration.rd-userprofile-api.client-secret
        - name: idam-user-profile-bridge-rd-system-username
          alias: rd.userprofile.client.registration.service-account-user
        - name: idam-user-profile-bridge-rd-system-password
          alias: rd.userprofile.client.registration.service-account-password
        - name: redis-hostname
          alias: spring.data.redis.host
        - name: redis-key
          alias: spring.data.redis.password
        - name: redis-port
          alias: spring.data.redis.port
