global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: sandbox
  enableKeyVaults: true

java:
  releaseNameOverride: idam-testing-support-api
  applicationPort: 5000
  image: 'hmctspublic.azurecr.io/idam/idam-testing-support-api:latest'
  ingressHost: idam-testing-support-api.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: idam
  environment:
    IDAM_API_URL: http://idam-api.service.core-compute-{{ .Values.global.environment }}.internal
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://idam-web-public.service.core-compute-{{ .Values.global.environment }}.internal/o/jwks
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_IDAMTESTINGSUPPORTAPI_TOKENURI: http://idam-web-public.service.core-compute-{{ .Values.global.environment }}.internal/o/token
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_RDUSERPROFILEAPI_TOKENURI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o/token
    RD_USERPROFILE_API_URL: http://rd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    RD_CASEWORKER_API_URL: http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_S2S-AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    "idam-idam":
      resourceGroup: idam-idam
      excludeEnvironmentSuffix: false
      secrets:
        - name: AppInsightsConnectionString
          alias: app-insights-connection-string
        - name: idam-api-POSTGRES-HOST       # Using idam-api DB Host for sandbox
          alias: DATASOURCE_HOST
        - name: idam-api-POSTGRES-PORT       # Using idam-api DB Port for sandbox
          alias: DATASOURCE_PORT
        - name: idam-api-POSTGRES-DATABASE   # Overriding to point to idam-api DB instead of old testing support DB
          alias: DATASOURCE_DATABASE
        - name: idam-api-POSTGRES-USER       # Using idam-api DB User for sandbox
          alias: spring.datasource.username
        - name: idam-api-POSTGRES-PASS       # Using idam-api DB Password for sandbox
          alias: spring.datasource.password
        - name: notify-api-key
          alias: notify.key
        - name: idam-testing-support-api-client-secret
          alias: spring.security.oauth2.client.registration.idam-testing-support-api.client-secret
        - name: idam-testing-support-api-client-secret
          alias: spring.security.oauth2.client.registration.rd-userprofile-api.client-secret
        - name: idam-user-profile-bridge-rd-system-username
          alias: rd.userprofile.client.registration.service-account-user
        - name: idam-user-profile-bridge-rd-system-password
          alias: rd.userprofile.client.registration.service-account-password
        - name: redis-hostname
          alias: spring.data.redis.host
        - name: redis-key
          alias: spring.data.redis.password
        - name: redis-port
          alias: spring.data.redis.port

