server:
  port: 5000

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: "always"
    info:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}

idam:
  api:
    url: http://dummy-api

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: idam-testing-support-api
  config:
    import: "optional:configtree:/mnt/secrets/idam-idam/"
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true
