server:
  port: 5000

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: "always"
    info:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}

idam:
  api:
    url: http://idam-api
  client:
    registration:
      id: idam-testing-support-api

spring:
  application:
    name: idam-testing-support-api
  config:
    import: "optional:configtree:/mnt/secrets/idam-idam/"
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://idam-api/o/jwks
      client:
        registration:
          idam-testing-support-api:
            authorization-grant-type: client_credentials
            client-id: idam-testing-support
            client-secret: idam-testing-support
            client-authentication-method: client_secret_post
            redirect-uri: http://idam-testing-support
            scope:
              - profile
              - manage-user
        provider:
          idam-testing-support-api:
            token-uri: http://idam-api/o/token

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}?sslmode=require&stringtype=unspecified
    username: dummy
    password: dummy
    properties:
      charSet: UTF-8
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true

feign:
  client:
    config:
      default:
        errorDecoder: uk.gov.hmcts.cft.idam.api.v2.common.error.SpringWebClientErrorDecoder
        retryer: uk.gov.hmcts.cft.idam.api.v2.common.error.SpringWebClientRetryer

scheduler:
  enabled: true
  initialDelayMs: 60000
  burner:
    triggerExpiryFrequencyMs: 360000
  session:
    triggerExpiryFrequencyMs: 3600000

cleanup:
  burner:
    lifespan: 1m
  session:
    lifespan: 5m
