server:
  port: 5000

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: "always"
    info:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}

idam:
  api:
    url: http://idam-api
  client:
    registration:
      id: idam-testing-support-api
  s2s-auth:
    microservice: rd_profile_sync
    totp_secret: dummy
    url: dummy

rd:
  userprofile:
    client:
      registration:
        id: rd-userprofile-api
        service-account-user: dummy
        service-account-password: dummy
    api:
      url: dummy
  caseworker:
    api:
      url: dummy

cft:
  categories:
    role-patterns:
      judiciary:
        - judiciary
      caseworker:
        - caseworker-.*
        - caseworker
        - cwd-user
      professional:
        - pui-.*
        - solicitor
      citizen:
        - citizen

notify:
  key: dummy
  maxPages: 20

spring:
  application:
    name: idam-testing-support-api
  config:
    import: "optional:configtree:/mnt/secrets/idam-idam/"
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    openfeign:
      client:
        config:
          default:
            errorDecoder: uk.gov.hmcts.cft.idam.api.v2.common.error.SpringWebClientErrorDecoder
            retryer: uk.gov.hmcts.cft.idam.api.v2.common.error.SpringWebClientRetryer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://idam-web-public/o/jwks
      client:
        registration:
          idam-testing-support-api:
            authorization-grant-type: client_credentials
            client-id: idam-testing-support-api
            client-secret: dummy
            client-authentication-method: client_secret_post
            redirect-uri: https://idam-testing-support-api
            scope:
              - profile
              - create-active-user
              - view-user
              - delete-user
              - update-user
              - update-user-password
              - create-role
              - delete-role
              - create-service-provider
              - delete-service-provider
              - archive-user
              - search-invitation
          rd-userprofile-api:
            authorization-grant-type: password
            client-id: idam-testing-support-api
            client-secret: dummy
            client-authentication-method: client_secret_post
            scope:
              - openid
              - profile
              - roles
              - create-user
              - manage-user
        provider:
          idam-testing-support-api:
            token-uri: http://idam-web-public/o/token
          rd-userprofile-api:
            token-uri: http://idam-web-public/o/token
  jackson:
    default-property-inclusion: non_null
  artemis:
    mode: embedded
    broker-url: tcp://localhost:61616
    embedded:
      enabled: true
      queues:
      - cleanup-role
      - cleanup-service
      - cleanup-session
      - cleanup-user

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}?sslmode=require&stringtype=unspecified
    username: dummy
    password: dummy
    properties:
      charSet: UTF-8
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

scheduler:
  enabled: true
  initialDelayMs: 60000
  burner:
    triggerExpiryFrequencyMs: 360000
  session:
    triggerExpiryFrequencyMs: 3600000

cleanup:
  burner:
    lifespan: 15m
    batch-size: 40
  session:
    lifespan: 2h
    batch-size: 20
  user:
    strategy: ALWAYS_DELETE
    recent-login-duration: 15m

featureFlags:
  s2sTestingSupportEnabled: true
  addEmailToNotifyReference: false
